[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-goforit = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["goforit/tests"]
python_files = ["test_*.py"]
asyncio_mode = "strict"